name = "serverless-qrcode-hub"
main = "index.js"
compatibility_date = "2025-03-10"

[[d1_databases]]
binding = "DB"
database_name = "hui_qrcode_hub"
# 注意：将下面的 id 替换为你自己拷贝的 D1 存储的 id 才能正常使用！
database_id = "50b83f01-c826-4bf3-b521-299dd34f316d"

[triggers]
crons = ["0 2 */1 * *"]

[[env.dev.d1_databases]]
binding = "DB"
database_name = "hui_qrcode_hub"
database_id = "50b83f01-c826-4bf3-b521-299dd34f316d"

[env.dev.triggers]
crons = ["*/10 * * * * *"]

[assets]
directory = "./dist"
binding = "ASSETS"
